---
- name: Install required packages on remote server
  hosts: aws_server
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: Install packages
      apt:
        name:
          - git
          - docker-compose
          - python3-pip
          - cockpit
          - cockpit-machines
          - cockpit-storaged 
        state: present
