---
- name: Basic Setup Role
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - basic_setup

- name: KVM Setup Role
  hosts: gcp_server
  become: yes
  gather_facts: no
  collections:
    - community.libvirt
  roles:
    - kvm_setup
