---
- name: Basic Setup Role
  hosts: all
  become: yes
  roles:
    - basic_setup

- name: KVM Setup Role
  hosts: gcp_workers
  become: yes
  collections:
    - community.libvirt
  roles:
    - kvm_setup
