---
- name: Basic Setup Role
  hosts: localhost
  become: yes
  gather_facts: yes
  tags: basic_setup
  roles:
    - basic_setup
  vars:
    # Define the user that should be added to docker group and other system groups
    ansible_user: "{{ ansible_user_id | default(ansible_env.USER | default('root')) }}"
    # Alternative: you can specify a specific username
    # ansible_user: "your_username"

- name: KVM Setup Role
  hosts: localhost
  become: yes
  gather_facts: no
  tags: kvm_setup
  collections:
    - community.libvirt
  vars_files:
    - "custom-underlay.yaml"
  roles:
    - kvm_setup


---
- name: Setup Application Framework
  hosts: all
  become: yes
  tags: appframework
  roles:
    - role: appframework
      vars:
        multi_vm: "no"  # Change to "yes" for multi-VM setup
        # vm_data: {}   # Add your VM data here if needed
