---
- name: Basic Setup Role
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - basic_setup
  when: ansible_distribution == 'Ubuntu

- name: KVM Setup Role
  hosts: gcp_server
  become: yes
  gather_facts: no
  collections:
    - community.libvirt
  roles:
    - kvm_setup
  when: ansible_distribution == 'Ubuntu'

# - name: Docker Setup Role
#   hosts: docker_hosts
#   become: yes
#   gather_facts: yes
#   roles:
#     - docker_setup
#   when: ansible_distribution == 'Ubuntu'

