---
# Main playbook that runs roles once and creates per-role marker files to avoid re-running
# Use 'force_reapply=true' to force roles to run again

---
- name: Basic Setup Role
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - basic_setup
  when: ansible_distribution == 'Ubuntu

- name: KVM Setup Role
  hosts: gcp_server
  become: yes
  gather_facts: no
  collections:
    - community.libvirt
  roles:
    - kvm_setup


