---
- name: Basic Setup Role
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - basic_setup
  when: ansible_distribution == 'Ubuntu'

- name: KVM Setup Role
  hosts: gcp_server
  become: yes
  gather_facts: no
  collections:
    - community.libvirt
  vars_files:
    - "custom-underlay.yaml"
  roles:
    - kvm_setup
